const FontFamily = {
    OpenSansBold: 'OpenSans-Bold',
    OpenSansBoldItalic: 'OpenSans-BoldItalic',
    OpenSansExtraBold: 'OpenSans-ExtraBold',
    OpenSansExtraBoldItalic: 'OpenSans-ExtraBoldItalic',
    OpenSansItalic: 'OpenSans-Italic',
    OpenSansLight: 'OpenSans-Light',
    OpenSansLightItalic: 'OpenSans-LightItalic',
    OpenSansMedium: 'OpenSans-Medium',
    OpenSansMediumItalic: 'OpenSans-MediumItalic',
    OpenSansRegular: 'OpenSans-Regular',
    OpenSansSemiBold: 'OpenSans-SemiBold',
    OpenSansSemiBoldItalic: "OpenSans-SemiBoldItalic",
    MONTSERRAT_Black: 'Montserrat-Black',
    MONTSERRAT_BlackItalic: 'Montserrat-BlackItalic',
    MONTSERRAT_Bold: 'Montserrat-Bold',
    MONTSERRAT_BoldItalic: 'Montserrat-BoldItalic',
    MONTSERRAT_ExtraBold: 'Montserrat-ExtraBold',
    MONTSERRAT_ExtraBoldItalic: 'Montserrat-ExtraBoldItalic',
    MONTSERRAT_ExtraLight: 'Montserrat-ExtraLight',
    MONTSERRAT_ExtraLightItalic: 'Montserrat-ExtraLightItalic',
    MONTSERRAT_Italic: 'Montserrat-Italic',
    MONTSERRAT_Light: 'Montserrat-Light',
    MONTSERRAT_LightItalic: 'Montserrat-LightItalic',
    MONTSERRAT_Medium: 'Montserrat-Medium',
    MONTSERRAT_MediumItalic: 'Montserrat-MediumItalic',
    MONTSERRAT_Regular: 'Montserrat-Regular',
    MONTSERRAT_SemiBold: 'Montserrat-SemiBold',
    MONTSERRAT_SemiBoldItalic: 'Montserrat-SemiBoldItalic',
    MONTSERRAT_Thin: 'Montserrat-Thin',
    MONTSERRAT_ThinItalic: 'Montserrat-ThinItalic',

}
export default FontFamily

