/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei/native";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
    nodes: {
        Outfit_Top: THREE.Mesh;
        Outfit_Footwear: THREE.Mesh;
        Outfit_Bottom: THREE.Mesh;
    };
    materials: {
        ["Wolf3D_Outfit_Top.001"]: THREE.MeshStandardMaterial;
        ["Wolf3D_Outfit_Footwear.001"]: THREE.MeshStandardMaterial;
        ["Wolf3D_Outfit_Bottom.001"]: THREE.MeshStandardMaterial;
    };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
    const { nodes, materials } = useGLTF(require(
        "../assets/3DModel/Character_1_Costume_1.glb")
    ) as GLTFResult;
    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Outfit_Top.geometry}
                material={materials["Wolf3D_Outfit_Top.001"]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Outfit_Footwear.geometry}
                material={materials["Wolf3D_Outfit_Footwear.001"]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Outfit_Bottom.geometry}
                material={materials["Wolf3D_Outfit_Bottom.001"]}
            />
        </group>
    );
}

useGLTF.preload(require(
    "../assets/3DModel/Character_1_Costume_1.glb"));

